### ISSUE TITLE
RuntimeError and NameError

### ISSUE THREAD

**Issue by SENLIER** [saibalmars/GraphRicciCurvature#10]
Hi, maybe there are some of my stupid mistakes.

When I run `example.py`,it The following error occurred.

>         RuntimeError:
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable

When I run `tutorial notebook`，it didn‘t work.

> RemoteTraceback                           Traceback (most recent call last)
> RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Anaconda3\lib\multiprocessing\pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "C:\Users\Administrator\Anaconda3\lib\site-packages\graphriccicurvature-0.3.1-py3.7.egg\GraphRicciCurvature\OllivierRicci.py", line 279, in _wrap_compute_single_edge
>     return _compute_ricci_curvature_single_edge(*stuff)
>   File "C:\Users\Administrator\Anaconda3\lib\site-packages\graphriccicurvature-0.3.1-py3.7.egg\GraphRicciCurvature\OllivierRicci.py", line 250, in _compute_ricci_curvature_single_edge
>     if _apsp[source][target] < EPSILON:
> NameError: name '_apsp' is not defined
> """
> 
> The above exception was the direct cause of the following exception:
> 
> NameError                                 Traceback (most recent call last)
> <ipython-input-18-21532f2f29e1> in <module>
> ----> 1 orc.compute_ricci_curvature()
>       2 G_orc = orc.G.copy()  # save an intermediate result
> 
> ~\Anaconda3\lib\site-packages\graphriccicurvature-0.3.1-py3.7.egg\GraphRicciCurvature\OllivierRicci.py in compute_ricci_curvature(self)
>     511                                           alpha=self.alpha, method=self.method,
>     512                                           base=self.base, exp_power=self.exp_power,
> --> 513                                           proc=self.proc, chunksize=self.chunksize)
>     514         return self.G
>     515 
> 
> ~\Anaconda3\lib\site-packages\graphriccicurvature-0.3.1-py3.7.egg\GraphRicciCurvature\OllivierRicci.py in _compute_ricci_curvature(G, weight, **kwargs)
>     356 
>     357     # Assign edge Ricci curvature from result to graph G
> --> 358     for rc in edge_ricci:
>     359         for k in list(rc.keys()):
>     360             source, target = k
> 
> ~\Anaconda3\lib\multiprocessing\pool.py in next(self, timeout)
>     746         if success:
>     747             return value
> --> 748         raise value
>     749 
>     750     __next__ = next                    # XXX
> 
> NameError: name '_apsp' is not defined

Platform

- OS: [e.g. Windows]
- Python [e.g. 3.7]
- Version [e.g. latest]

**Comment by saibalmars** [comment]
Hi, thanks for mention this, I guess it's because I didn't define global variable _apsp in each function, please try [this](https://github.com/saibalmars/GraphRicciCurvature/tree/global ) branch to see if this solve your problem.

**Comment by saibalmars** [comment]
Fix in the [latest release].(https://github.com/saibalmars/GraphRicciCurvature/releases/tag/v0.4)
