### ISSUE TITLE
I can't install this package(https://github.com/saibalmars/GraphRicciCurvature.git)

### ISSUE THREAD

**Issue by S0MENTEANDRE** [saibalmars/GraphRicciCurvature#2]
I'm try install with: pip install git+https://github.com/saibalmars/GraphRicciCurvature.git
But result in: 
Collecting git+https://github.com/saibalmars/GraphRicciCurvature.git
  Cloning https://github.com/saibalmars/GraphRicciCurvature.git to /private/var/folders/yj/cx50wr6972528jw1r3vnr2xc0000gn/T/pip-req-build-_j8hsf6u
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/anaconda3/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/yj/cx50wr6972528jw1r3vnr2xc0000gn/T/pip-req-build-_j8hsf6u/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/yj/cx50wr6972528jw1r3vnr2xc0000gn/T/pip-req-build-_j8hsf6u/

**Comment by saibalmars** [comment]
Hi, currently the package is not on pip yet, I will find some time to put it on pip. In the meanwhile, please just clone the repo or download the zip to use it.

**Comment by saibalmars** [comment]
Now the package can be installed via pip as follows:
`pip3 install GraphRicciCurvature`.

**Comment by S0MENTEANDRE** [comment]
Yes. I was installing without pip some time ago. Thanks for responding the
issue

Em qua, 3 de jul de 2019 às 19:45, saibalmars <notifications@github.com>
escreveu:
