### ISSUE TITLE
Kernel dies on my MacBook and multiprocess not run on Windows 10

### ISSUE THREAD

**Issue by xywu-soc** [saibalmars/GraphRicciCurvature#38]
Hi,

I'm trying to run this package on both my MacBook and Windows 10 machines. However, I cannot get it run on either one.
I'm trying with codes in your example.py, the first example using OllivierRicci().

On my MacBook, the kernel dies as soon as I run 'orc.compute_ricci_curvature()'.
On my Windows 10 desktop, I have to use 'spawn' for multiprocessing as neither 'fork' nor 'forkserver' is available for Windows. The program just hangs in the same line, 'orc.compute_ricci_curvature()'.

Is there any way to get around these issues, on any of the machines? Or this package only runs on particular machines?

Many thanks in advance!

**Comment by saibalmars** [comment]
Hi I tried on MacBook Pro with both Intel and M1 without any problems, can you attached the error code for further investigation?
Since I don't have a windows machine to test, I would suggest run the code inside WSL, it will give you a better compatibility for python too.

**Comment by AlenaResiko** [comment]
Hi,


I was wondering if you were able to resolve this issue? I am experiencing similar problem: when running orc.compute_ricci_curvature() on Windows, I get 

> raise ValueError('cannot find context for %r' % method) from None
> ValueError: cannot find context for 'fork'

Do you have any suggestions on what I could potentially do?

**Comment by saibalmars** [comment]
Hi @AlenaResiko, the problem is due to Windows's fork issue. The only solution to run on Windows now is to run it inside [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). Sorry about the inconvenience.

**Comment by AlenaResiko** [comment]
> Hi @AlenaResiko, the problem is due to Windows's fork issue. The only solution to run on Windows now is to run it inside [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). Sorry about the inconvenience.

Thank you!
By the way, the program runs perfectly on MacBook Air M1.

**Comment by xywu-soc** [comment]
> Hi I tried on MacBook Pro with both Intel and M1 without any problems, can you attached the error code for further investigation? Since I don't have a windows machine to test, I would suggest run the code inside WSL, it will give you a better compatibility for python too.

Hi, thank you so much for the reply! I was in conference travelling without a compatible machine to try on when receiving the reply, and we were distracted by some other unexpected issues on that project later on. Sorry for the delayed response.

It works perfectly on both newer MacBook and Linux-based virtual machines. Thank you so much for this great package and the help!
