### ISSUE TITLE
Error in Discrete Ricci Curvature tutorial

### ISSUE THREAD

**Issue by JianingF** [saibalmars/GraphRicciCurvature#41]
I believe there is a small error in the tutorial for Discrete Ricci curvature. The probability distribution is defined as having weight alpha for x and weight 1 - alpha for a neighbor of x, but the weight for the neighbors of x should be divided by the number of neighbors of x so that the total weight is 1.

**Comment by saibalmars** [comment]
Thanks, it's been fixed in 724a950272dee7f84ac9f4c2eb8224d651924a28
