### ISSUE TITLE
Dear Ni, a question to ask.

### ISSUE THREAD

**Issue by peter308** [saibalmars/GraphRicciCurvature#43]
Dear Ni

Many thanks to the code you shared. I would like to ask one question.

In calculating the Olliver-Ricci flow, the edge weights will change while updating ORC in each round.

Is it possible that the edge weights can be constrained between 1 to a maximum value?

Because the edge weights in my case have a physical meaning, and if it drops to zero, it could generate unphysical results.

Thanks.

best regards,
Peter

**Comment by saibalmars** [comment]
Hi Peter, 
Thanks for your interest of our work :)

I didn't try it myself, but I guess you can "shift" all edge weights to the direction you want during the [normalization step](https://github.com/saibalmars/GraphRicciCurvature/blob/724a950272dee7f84ac9f4c2eb8224d651924a28/GraphRicciCurvature/OllivierRicci.py#L583). In current edge weight normalization, we simply make sure the sum of all weight to be the same during each Ricci flow computation and that should be the place for you to start.

**Comment by peter308** [comment]
Dear Ni

Thanks. I will work on the normalization of the weights. Appreciate the suggestions.

with regards,
Peter
