### ISSUE TITLE
ricciCurvature_singleEdge()  TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by deryc** [saibalmars/GraphRicciCurvature#5]
Using a basic .gml file with the following format

`edge`
`[`
`    source 1136`
`    target 3710`
`    value 2.000`
`]`

and my code looks like

`G = nx.read_gml(file,['utf-8']) `
`G = nx.Graph(G)`
`G = ricciCurvature_singleEdge(G, alpha = 0.5, source = '1136', target = '3710', length = 1, verbose = True) `

which gives me the error

`Type Error: 'int' object is not subscriptable`

**Comment by saibalmars** [comment]
I'm guessing you didn't load the graph correctly, can you try to load the graph via edge lists?
Also, for `ricciCurvature_singleEdge`, the `length` parameter should be the shortest path dictionary, I will try to write an example for that function later, please use `ricciCurvature` for now.

**Comment by saibalmars** [comment]
In current branch https://github.com/saibalmars/GraphRicciCurvature/tree/ricci_flow you can call `compute_ricci_curvature_edges` to compute a single edges or list of edges now.
