### ISSUE TITLE
Not compatible with any version of networkX?

### ISSUE THREAD

**Issue by gintepe** [saibalmars/GraphRicciCurvature#8]
It seems there are slight migration issues. I was trying to run the sample code, and it seems that there are part of the code that are not compatible with networkX 2.x (primarily calling G.node instead of G.nodes) and other parts incompatible with networkX 1.x (swapped order of arguments in one of the function calls). 
I have made a couple of fixes to make it work with the newest version of networkX that I could submit if that would be helpful.

**Comment by saibalmars** [comment]
Hi @gintepe, thanks for the notice, it seems that NetworkX just removed G.node in their recent release of 2.4, I will fix it in the next version very soon.

Meanwhile, can you suggest which function is incompatible with 1.x? Thanks!

**Comment by gintepe** [comment]
There is a fucntion call in compute_ricci_flow which has the wrong argument order for networkX 1.x - line 421 in OllivierRicci.py 

According to a migration guide, "The order of arguments to set_edge_attributes and set_node_attributes has changed. The position of name and values has been swapped, and name now defaults to None. The previous call signature of (graph, name, value) has been changed to (graph, value, name=None)."

Older networkX tries to hash the dict w as the name and thus crashes.

**Comment by saibalmars** [comment]
Solved in https://github.com/saibalmars/GraphRicciCurvature/pull/9/commits/01772b6d8c239f153165cdd457a5e6db79182962.

Now it's compatable with NetworkX version > 2.0. For NetworkX 1.X, since `G.nodes` is not supported, I guess you need to manually change it to `G.node` for now.
